version: '3.8'
services:
 db:
   container_name: postgres_container
   image: postgres
   restart: always
   env_file: .env
   environment:
     POSTGRES_DB: postgres_db
     POSTGRES_USER: ${POSTGRES_USERNAME}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     PGDATA: /var/lib/postgresql/data
   ports:
     - ${POSTGRES_PORT}:5432
   volumes:
     - db-data:/var/lib/postgresql/data

 pgadmin:
   container_name: pgadmin4_container
   image: dpage/pgadmin4
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
     PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
     PGADMIN_LISTEN_PORT: ${PG_LISTEN_PORT}
   ports:
     - ${PG_PORT}:80
   volumes:
     - pgadmin-data:/var/lib/pgadmin
volumes:
 db-data:
 pgadmin-data:
